#!/usr/bin/expect -f

if { $argc != 2 } {
    puts stderr "usage: ./expt host pass"
    exit 2
}

   set host [lindex $argv 0]
   set pass [lindex $argv 1]

   spawn ssh-copy-id $host
   expect "connecting (yes/no)?"
   send "yes\n"
   expect "assword:"
   send "$pass\n"
   expect eof
